# ЭТАП 1: Сборка (Build)
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

# Копируем pom.xml и скачиваем зависимости (чтобы кэшировалось)
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Копируем исходный код и собираем
COPY src ./src
RUN mvn clean package -DskipTests

# ЭТАП 2: Запуск (Run)
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# Копируем JAR файл (используем wildcard *, чтобы не зависеть от версии в имени)
COPY --from=build /app/target/*.jar app.jar

# Порт, который слушает приложение
EXPOSE 8080

# Команда запуска
ENTRYPOINT ["java", "-jar", "app.jar"]
