# ЭТАП 1: Сборка (Build)
# Используем образ Maven с Java 17 (Eclipse Temurin - надежный стандарт)
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

# Копируем файлы
COPY . .

# Собираем
RUN mvn clean package -DskipTests

# ЭТАП 2: Запуск (Run)
# Используем легкую версию Java 17 для запуска
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# Копируем JAR
COPY --from=build /app/target/psycho-0.0.1-SNAPSHOT.jar app.jar

# Порт
EXPOSE 8080

# Запуск
ENTRYPOINT ["java", "-jar", "app.jar"]