# ЭТАП 1: Сборка (Build)
# Используем надежный образ Eclipse Temurin JDK 17
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

# Копируем код
COPY . .

# Собираем (пропускаем тесты для скорости)
RUN mvn clean package -DskipTests

# ЭТАП 2: Запуск (Run)
# Используем легкую версию JRE для запуска
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# !!! ВАЖНОЕ ИСПРАВЛЕНИЕ ТУТ !!!
# Вместо конкретного имени (psycho...) используем звездочку *.jar
# Это спасет от ошибки "File not found"
COPY --from=build /app/target/*.jar app.jar

# Открываем порт
EXPOSE 8080

# Запускаем
ENTRYPOINT ["java", "-jar", "app.jar"]