CREATE TABLE IF NOT EXISTS clinics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    city VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    email VARCHAR(255),
    description VARCHAR(2000),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    clinic_id BIGINT NOT NULL,
    CONSTRAINT fk_departments_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id)
);

CREATE TABLE IF NOT EXISTS clinic_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1500),
    duration_minutes INTEGER NOT NULL,
    base_price NUMERIC(12, 2) NOT NULL,
    department_id BIGINT NOT NULL,
    CONSTRAINT fk_services_department FOREIGN KEY (department_id) REFERENCES departments (id)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    specialization VARCHAR(255),
    license_number VARCHAR(255),
    years_of_experience INTEGER,
    about VARCHAR(3000),
    clinic_id BIGINT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_users_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id)
);

CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    psychologist_id BIGINT NOT NULL,
    clinic_id BIGINT,
    department_id BIGINT,
    medical_service_id BIGINT,
    appointment_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    status VARCHAR(255) NOT NULL,
    complaint VARCHAR(2000),
    diagnosis VARCHAR(3000),
    treatment_plan VARCHAR(3000),
    notes VARCHAR(4000),
    cancellation_reason VARCHAR(1000),
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_appointments_client FOREIGN KEY (client_id) REFERENCES users (id),
    CONSTRAINT fk_appointments_psychologist FOREIGN KEY (psychologist_id) REFERENCES users (id),
    CONSTRAINT fk_appointments_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id),
    CONSTRAINT fk_appointments_department FOREIGN KEY (department_id) REFERENCES departments (id),
    CONSTRAINT fk_appointments_service FOREIGN KEY (medical_service_id) REFERENCES clinic_services (id),
    CONSTRAINT fk_appointments_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS appointment_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    text VARCHAR(4000) NOT NULL,
    metadata VARCHAR(3000),
    event_time TIMESTAMP NOT NULL,
    CONSTRAINT fk_events_appointment FOREIGN KEY (appointment_id) REFERENCES appointments (id),
    CONSTRAINT fk_events_sender FOREIGN KEY (sender_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name VARCHAR(255) NOT NULL,
    entity_id BIGINT NOT NULL,
    action VARCHAR(255) NOT NULL,
    actor_id BIGINT NOT NULL,
    actor_email VARCHAR(255) NOT NULL,
    details VARCHAR(5000),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS knowledge_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    summary VARCHAR(1500),
    content TEXT NOT NULL,
    category VARCHAR(255) NOT NULL,
    tags VARCHAR(500),
    published BOOLEAN NOT NULL DEFAULT FALSE,
    author_id BIGINT,
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_articles_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);
CREATE INDEX IF NOT EXISTS idx_appointments_client ON appointments (client_id);
CREATE INDEX IF NOT EXISTS idx_appointments_psychologist ON appointments (psychologist_id);
CREATE INDEX IF NOT EXISTS idx_appointments_time ON appointments (appointment_time);
CREATE INDEX IF NOT EXISTS idx_events_appointment_time ON appointment_events (appointment_id, event_time);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_events (entity_name, entity_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_published ON knowledge_articles (published, category);
